ARG version
FROM almalinux:${version}
ARG name
ARG course
RUN echo "i am ${name} course is ${course}"
CMD [ "sleep", "100" ]
#default args declaration
ARG ${name:-vishnu}
ARG ${course:-docker}

# CMD [ "sleep", "100" ]


