# ARG version
# FROM almalinux:9
# ARG name
# ARG course
# ENV duration=112hrs
# RUN echo "i am ${name} course is ${course}"
# CMD [ "sleep", "200" ]

FROM almalinux:9
ARG name
ARG course
ARG duration
ENV duration=2323
RUN echo "i am ${name} course is ${course} duration is ${duration}}"
CMD [ "sleep", "200" ]

